services:
  my-app:
    build: .
    container_name: furniture-golang-be
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - postgre-hari-network
    command: >
      sh -c "
        ./migrate -path pkg/database/migrations -database 'postgres://$${DB_USER}:$${DB_PASSWORD}@$${DB_HOST}:$${DB_PORT}/$${DB_NAME}?sslmode=disable' up &&
        ./main
      "

networks:
  postgre-hari-network:
    external: true