services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: furniture-golang-be
    restart: always
    env_file:
      - prod.env
    ports:
      - "8083:8080"
    networks:
      - postgre-hari-network
    

networks:
  postgre-hari-network:
    external: true