services:
  # Hanya definisikan layanan aplikasi Anda
  my-app:
    build: .
    container_name: furniture-golang-be # Sebaiknya beri nama unik
    restart: always
    env_file:
      - ./prod.env # File ini berisi info koneksi ke DB
    ports:
      - "8003:8080"
    networks:
      # Hubungkan ke jaringan tempat Postgre berada
      - postgre-hari-network
    command: >
      sh -c "
        migrate -path pkg/database/migrations -database 'postgres://$${DB_USER}:$${DB_PASSWORD}@$${DB_HOST}:$${DB_PORT}/$${DB_NAME}?sslmode=disable' up &&
        /main
      "

# Beritahu Docker Compose bahwa jaringan ini sudah ada di luar sana
networks:
  postgre-hari-network:
    external: true